set autochdir
syntax enable                                               "" turn on all magic, including Explorer and syntax highlighting
syntax on
set showmode                                                "" show me when I am in insert or overtype mode
set showcmd                                                 "" when a command is in progress, show it in the status bar

set wildmenu magic                                          "" for completion at the : command line.
set ruler                                                   "" turn on the "ruler" (status info) at the bottom of the screen
set hlsearch                                                "" highlight all matches in text when you search
set showmatch                                               "" show matches for braces, parens, etc.
set spelllang=en_us                                         "" when I want spell-checking, I want it to be english
set spell

set nocompatible
filetype plugin on

set background=dark
"set background=light
color desert                                                "" ls /usr/share/vimNN/colors

"hi comment ctermbg=blue
"hi string ctermbg=green
"
set ts=4 sts=4 sw=4 et
set tw=125 fo+=tcq wm=0
set foldmethod=indent
 
set cursorline
set cursorcolumn
set colorcolumn=125

hi CursorLine cterm=NONE ctermbg=grey ctermfg=black
hi CursorColumn cterm=NONE ctermbg=darkgreen ctermfg=black
hi ColorColumn cterm=NONE ctermbg=red ctermfg=black

if &diff
    highlight! link DiffText MatchParen
endif
